site_name: SCRAPINGAI
site_description: AI-powered web scraping tools and techniques
site_author: sodown4thecause
repo_url: https://github.com/sodown4thecause/SCRAPINGAI
repo_name: sodown4thecause/SCRAPINGAI

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - API Reference: api-reference.md
  - Examples: examples.md
  - Contributing: contributing.md

plugins:
  - search